<?php

declare(strict_types=1);

/*
 * EnumAsTemplateParameterExampleAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace EnumAsTemplateParameterExampleAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use EnumAsTemplateParameterExampleAPILib\Models\ItemsResponse;

/**
 * Builder for model ItemsResponse
 *
 * @see ItemsResponse
 */
class ItemsResponseBuilder
{
    /**
     * @var ItemsResponse
     */
    private $instance;

    private function __construct(ItemsResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new items response Builder object.
     */
    public static function init(): self
    {
        return new self(new ItemsResponse());
    }

    /**
     * Sets id field.
     */
    public function id(?int $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets name field.
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets status field.
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Initializes a new items response object.
     */
    public function build(): ItemsResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
